#!/usr/bin/env python3
from argparse import ArgumentParser
from scope.mplscope import MplScope
from scope.datasource.factory import DataSourceFactory
import sys


def main():
    parser = ArgumentParser(description='Python oscilloscope')

    parser.add_argument('--fft', action='store_true', help='show FFT below time domain plot')
    subparser = parser.add_subparsers(required=True, dest='datasource')

    ds_factory = DataSourceFactory()
    ds_factory.add_parsers(subparser)

    args = parser.parse_args()

    scope = MplScope(fft=args.fft)
    scope.set_data_source(args.ds_class, **vars(args))
    scope.show()
    scope.stop_data_source()
    scope.save_data_csv('pyscope.csv')

    return 0


if __name__ == '__main__':
    sys.exit(main())
